"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BIRD_HUNGER_LANDING_DESIRE = exports.BIRD_COMMUNAL_LANDING_DESIRE = exports.BIRD_ALIGNMENT_EAGERNESS = exports.BIRD_COHESION_EAGERNESS = exports.BIRD_SEPARATION_EAGERNESS = exports.BIRD_SEPARATION_DISTANCE = exports.BIRD_EATING_SPEED = exports.LIVING_ENERGY_COST = exports.ACCELERATION_ENERGY_COST = exports.MAX_BIRD_ENERGY = exports.BIRD_VISUAL_RANGE = exports.BIRD_SPEED = exports.BIRD_HEIGHT = exports.BIRD_WIDTH = exports.BIRD_COUNT = exports.LayerIndex = void 0;
var LayerIndex;
(function (LayerIndex) {
    LayerIndex[LayerIndex["BACKGROUND"] = 0] = "BACKGROUND";
    LayerIndex[LayerIndex["BIRDS"] = 1] = "BIRDS";
    LayerIndex[LayerIndex["TOOLS"] = 2] = "TOOLS";
})(LayerIndex = exports.LayerIndex || (exports.LayerIndex = {}));
;
exports.BIRD_COUNT = 750;
exports.BIRD_WIDTH = 4;
exports.BIRD_HEIGHT = 2;
exports.BIRD_SPEED = 100 / 1000;
exports.BIRD_VISUAL_RANGE = 75;
exports.MAX_BIRD_ENERGY = 500;
exports.ACCELERATION_ENERGY_COST = 50 / 100;
exports.LIVING_ENERGY_COST = 10 / 1000;
exports.BIRD_EATING_SPEED = 150 / 1000;
exports.BIRD_SEPARATION_DISTANCE = 1.5 * Math.sqrt(exports.BIRD_WIDTH * exports.BIRD_WIDTH + exports.BIRD_HEIGHT * exports.BIRD_HEIGHT);
exports.BIRD_SEPARATION_EAGERNESS = 0.1;
exports.BIRD_COHESION_EAGERNESS = 0.01;
exports.BIRD_ALIGNMENT_EAGERNESS = 0.1;
exports.BIRD_COMMUNAL_LANDING_DESIRE = 1;
exports.BIRD_HUNGER_LANDING_DESIRE = 1;
